version: "3"

services:
    application:
        container_name: ${PROJECT_FOLDER_NAME}
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        env_file:
            - .env.test
        volumes:
            - ${PWD}/:/home/app/
        command: poetry run python runapp.py
        depends_on:
            test_database:
                condition: service_healthy
        networks:
            - flask-template-test

    test_database:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=db_secret
            - POSTGRES_USER=db_user
            - POSTGRES_DB=db_name
        networks:
            - flask-template-test
        healthcheck:
              test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U db_user -d db_name" ]
              interval: 5s
              timeout: 5s
              retries: 5

networks:
    flask-template-test:
      external: true
